[package]
name = "bitcaskplus"
version = "0.1.0"
authors = ["Grcm"]
edition = "2024"

[dependencies]
clap = "4.5.54"
tempfile = "3.24.0"
walkdir = "2"

[dev-dependencies]
assert_cmd = "2.1.2"
predicates = "3.1.3"
walkdir = "2.2.7"
